---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:5.3.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:5.3.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
