---
name: Studio Code Server
version: dev
slug: vscode
description: Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
url: https://github.com/hassio-addons/addon-vscode
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 1337
ingress_stream: true
panel_admin: true
panel_icon: mdi:microsoft-visual-studio-code
startup: services
init: false
arch:
  - aarch64
  - amd64
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
privileged:
  - SYS_ADMIN
full_access: true
map:
  - backup:rw
  - data:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
services:
  - mysql:want
  - mqtt:want
journald: true
options:
  log_level: warning
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  vscode_config_path: str?
  packages:
    - str?
  init_commands:
    - str?
