---
name: Studio Code Server
version: dev
slug: vscode
description: Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
url: https://github.com/hassio-addons/addon-vscode
ingress: true
ingress_port: 1337
ingress_stream: true
panel_icon: mdi:microsoft-visual-studio-code
startup: services
init: false
arch:
  - aarch64
  - amd64
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - media:rw
  - share:rw
  - backup:rw
services:
  - mysql:want
  - mqtt:want
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
    - str
  init_commands:
    - str
